"""empty message

Revision ID: 4a4ced5eec1a
Revises: 6de25cacef00
Create Date: 2018-06-24 18:52:04.440813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import table, column, Column
from sqlalchemy.sql.functions import now

revision = '4a4ced5eec1a'
down_revision = '6de25cacef00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column('confirmed_at')
    # ### end Alembic commands ###



def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    users = table('users',
        column('confirmed_at', sa.DateTime()),
    )

    op.get_bind().execute(
        users.update().values(confirmed_at=now()))