"""empty message

Revision ID: 6de25cacef00
Revises: 3e62893a6552
Create Date: 2017-01-08 18:20:10.725562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de25cacef00'
down_revision = '3e62893a6552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('views', sa.Integer(), server_default="0"))
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('_views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('views')
    # ### end Alembic commands ###

